version: '3.7'
services:
  lumen:
    build: ./build
    volumes:
      - .:/usr/src/myapp
    working_dir: /usr/src/myapp
    # CURRENT_UID=$(id -u):$(id -g)
    # user: ${CURRENT_UID}
    # command: tail -f /dev/null
    command: sh
    stop_signal: SIGKILL
